Module7 task3
htmlacademy-react/1033161-what-to-watch-5 pull request #14
Opened 2020-11-16 17:57 UTC by cactusjam

2020-11-16 21:37 UTC, DmitryMarkov requested changes
Некоторые пункты технического задания не выполнены:

> Пользователь выставляет оценку фильму от 1 до 5. Оценка выставляется путём выделения определённого количества звёзд.

По-умолчанию в форме выставлена 1 звезда, надо сделать, чтобы пользователь ставил сам

> Пока пользователь не поставил оценку и не ввел допустимый объём текста, кнопка отправки отзыва не активна.

Тоже нарушен из-за звезд

> При нажатии кнопки «Post» и отправки данных форма должна блокироваться. Разблокировка формы происходит в случае успешной отправки или при возникновении ошибки.

Форма не блокируется, кнопку можно нажать несколько раз

> В случае возникновения ошибки следует уведомить пользователя. Способ отображения ошибки остаётся на усмотрение разработчика.

Обработка ошибки и уведомление пользователя отсутствует

2020-11-16 21:37 UTC, DmitryMarkov commented on src/components/movie-screen/movie-screen.jsx
> +  }),
повторяется во многих компонентах, лучше вынести в шейп

2020-11-16 21:37 UTC, DmitryMarkov commented on src/components/player-screen/player-screen.jsx
> +// import {movieDetails} from "../../types/types";
комменты кода запрещены

2020-11-16 21:37 UTC, DmitryMarkov commented on src/store/api-actions.js
> +    .then(() => dispatch(redirectToRoute(AppRoute.MOVIES + `/${id}`)))
нет обработки ошибок

2020-11-19 03:50 UTC, DmitryMarkov reviewed
Замечания исправлены. По поводу рейтинга (в звездах) попробуй сделать так чтобы при загрузке страницы они не выглядели "выбранными", потому что сейчас они выглядят, как будто уже выбраны 5 звезд

2020-11-19 03:50 UTC, DmitryMarkov commented on src/components/movie-screen/movie-screen.jsx
> +                <Link to={`/mylist`} className="btn movie-card__button">My List</Link>
Эта кнопка не нужна. Переход на список нужно делать через аватарку (см. ТЗ)

> Клик по аватарке пользователя выполняет переход на страницу MyList (/mylist).

2020-11-19 03:50 UTC, DmitryMarkov commented on src/components/my-list-screen/my-list-screen.jsx
> +            </Link>
Разметку, которая повторяется из компонента в компонент лучше выносить в отдельные компоненты

2020-11-19 03:50 UTC, DmitryMarkov commented on src/store/api-actions.js
> +  });
Здесь тоже должен быть обработчик ошибок

2020-11-19 03:50 UTC, merged

2020-11-19 10:36 UTC, cactusjam commented
> Замечания исправлены. По поводу рейтинга (в звездах) попробуй сделать так чтобы при загрузке страницы они не выглядели "выбранными", потому что сейчас они выглядят, как будто уже выбраны 5 звезд

Просидела над этой задачей несколько дней и так и не сообразила как реализовать этот момент:(

2020-11-19 11:34 UTC, DmitryMarkov commented
@cactusjam можем созвониться, либо я пришлю решение. До защиты надо успеть исправить, время ещё есть

2020-11-19 14:49 UTC, cactusjam commented
> @cactusjam можем созвониться, либо я пришлю решение. До защиты надо успеть исправить, время ещё есть
пришли пожалуйста решение. мне на слух намного сложнее соориентироваться будет.