Module4 task2
htmlacademy-react/1033161-what-to-watch-5 pull request #7
Opened 2020-10-19 14:06 UTC by cactusjam

2020-10-19 22:29 UTC, DmitryMarkov requested changes
Задание выполнено, но с неточностями. Необходимо доработать компонент Tabs, чтобы он содержал верстку табов и принимал props для них

2020-10-19 22:29 UTC, DmitryMarkov commented on src/components/movie-screen/movie-screen.jsx
> +            <Tabs>
Я бы вынес в отдельный компонент, уж очень много верстки тут, трудно ориентироваться. К тому же в задании сказано что пропсы должен получать компонент "Табы"

2020-10-19 22:29 UTC, DmitryMarkov commented on src/components/movie-screen/movie-screen.jsx
> +              <Tab title={TabsName.OVERVIEW}>
```suggestion
              <Tab title={TabName.OVERVIEW}>
```

2020-10-19 22:29 UTC, DmitryMarkov commented on src/types/types.jsx
> +  genre: PropTypes.array.isRequired,
нужно заменить на arrayOf

2020-10-19 22:29 UTC, DmitryMarkov commented on src/types/types.jsx
> +  genre: PropTypes.array.isRequired,
⬆️

2020-10-19 22:29 UTC, DmitryMarkov commented on src/utils/utils.js
> +    return item.genre.some((it) => it === genre[0]) && item.title !== title;
лучше сравнение делать не по имени а id

2020-10-22 07:11 UTC, DmitryMarkov approved these changes
Задание выполнено

2020-10-22 07:11 UTC, DmitryMarkov commented on src/types/types.jsx
> +  genre: PropTypes.arrayOf.isRequired,
Нужно уточнять arrayOf... what :)

2020-10-22 07:11 UTC, DmitryMarkov commented on src/components/movie-reviews/movie-reviews.jsx
> +        </div>)}
Когда у нас многострочный JSX вывод, хороший тон заключать его в круглые скобки 
```suggestion
        {reviews.map((review) => (
          <div key={review.author} className="review">
            <blockquote className="review__quote">
              <p className="review__text">{review.text}</p>

              <footer className="review__details">
                <cite className="review__author">{review.author}</cite>
                <time className="review__date" dateTime="2016-12-24">{review.date}</time>
              </footer>
            </blockquote>

            <div className="review__rating">{review.rating}</div>
          </div>
          ))}
```

2020-10-22 07:12 UTC, merged

2020-10-22 10:28 UTC, cactusjam commented on src/types/types.jsx
> +  genre: PropTypes.arrayOf.isRequired,
упс:))